// @ts-nocheck
/**
 * plantCatalogSeed.ts
 *
 * Hand-authored STARTER catalog of common US landscape plants and materials so the
 * Design Studio's zone-aware selection + deterministic costing (see plantIntelligence.ts)
 * has real, defensible data with NO external API or scraping.
 *
 * SCOPE / HONESTY
 *  - ~36 entries: a curated cross-section of widely planted trees, shrubs, perennials/
 *    grasses/groundcovers, and common hardscape/mulch/edging materials.
 *  - Horticultural facts (USDA hardiness zone range, sun, mature size, spacing) are drawn
 *    from well-known, mainstream references (Missouri Botanical Garden Plant Finder, USDA
 *    PLANTS, NC State Extension, Rutgers deer-resistance ratings A..D). They are typical
 *    ranges for the species/cultivar named — real cultivars vary, so a contractor should
 *    still confirm against a local grower.
 *  - Prices are BALLPARK US retail + light install estimates (2024-era), not quotes.
 *    Adjust per region/market. unitPrice is in USD per `unit`; installLaborMinutes is the
 *    typical per-unit install time used by estimateLineItems().
 *  - Every included item is non-invasive (invasive: false). Known invasives (e.g. Bradford
 *    pear, burning bush, Japanese barberry, English ivy, butterfly bush in some regions)
 *    are deliberately EXCLUDED.
 *
 * deerRating uses the Rutgers scale: A = rarely damaged … D = frequently damaged.
 */

import type { PlantCatalogItem } from "./plantIntelligence";

export const PLANT_CATALOG_SEED: PlantCatalogItem[] = [
  // ------------------------------------------------------------------ TREES (8)
  {
    id: "tree-acer-rubrum-october-glory",
    name: "Red Maple 'October Glory'",
    botanicalName: "Acer rubrum 'October Glory'",
    kind: "plant",
    zoneMin: 4,
    zoneMax: 9,
    sun: ["full_sun", "part_sun"],
    matureHeightFt: 40,
    matureSpreadFt: 30,
    spacingFt: 30,
    native: true,
    invasive: false,
    deerRating: "C",
    unit: "each",
    unitPrice: 240,
    installLaborMinutes: 90,
  },
  {
    id: "tree-cornus-florida",
    name: "Flowering Dogwood",
    botanicalName: "Cornus florida",
    kind: "plant",
    zoneMin: 5,
    zoneMax: 9,
    sun: ["part_sun", "part_shade"],
    matureHeightFt: 20,
    matureSpreadFt: 22,
    spacingFt: 20,
    native: true,
    invasive: false,
    deerRating: "C",
    unit: "each",
    unitPrice: 180,
    installLaborMinutes: 75,
  },
  {
    id: "tree-lagerstroemia-crape-myrtle",
    name: "Crape Myrtle",
    botanicalName: "Lagerstroemia indica",
    kind: "plant",
    zoneMin: 7,
    zoneMax: 9,
    sun: ["full_sun"],
    matureHeightFt: 20,
    matureSpreadFt: 15,
    spacingFt: 15,
    native: false,
    invasive: false,
    deerRating: "B",
    unit: "each",
    unitPrice: 150,
    installLaborMinutes: 70,
  },
  {
    id: "tree-quercus-rubra",
    name: "Northern Red Oak",
    botanicalName: "Quercus rubra",
    kind: "plant",
    zoneMin: 4,
    zoneMax: 8,
    sun: ["full_sun"],
    matureHeightFt: 70,
    matureSpreadFt: 55,
    spacingFt: 45,
    native: true,
    invasive: false,
    deerRating: "C",
    unit: "each",
    unitPrice: 260,
    installLaborMinutes: 100,
  },
  {
    id: "tree-betula-nigra-river-birch",
    name: "River Birch",
    botanicalName: "Betula nigra",
    kind: "plant",
    zoneMin: 4,
    zoneMax: 9,
    sun: ["full_sun", "part_sun"],
    matureHeightFt: 50,
    matureSpreadFt: 40,
    spacingFt: 30,
    native: true,
    invasive: false,
    deerRating: "B",
    unit: "each",
    unitPrice: 200,
    installLaborMinutes: 90,
  },
  {
    id: "tree-magnolia-grandiflora",
    name: "Southern Magnolia",
    botanicalName: "Magnolia grandiflora",
    kind: "plant",
    zoneMin: 7,
    zoneMax: 9,
    sun: ["full_sun", "part_sun"],
    matureHeightFt: 60,
    matureSpreadFt: 40,
    spacingFt: 35,
    native: true,
    invasive: false,
    deerRating: "B",
    unit: "each",
    unitPrice: 230,
    installLaborMinutes: 95,
  },
  {
    id: "tree-amelanchier-serviceberry",
    name: "Serviceberry",
    botanicalName: "Amelanchier x grandiflora 'Autumn Brilliance'",
    kind: "plant",
    zoneMin: 4,
    zoneMax: 8,
    sun: ["full_sun", "part_sun", "part_shade"],
    matureHeightFt: 20,
    matureSpreadFt: 15,
    spacingFt: 15,
    native: true,
    invasive: false,
    deerRating: "C",
    unit: "each",
    unitPrice: 175,
    installLaborMinutes: 75,
  },
  {
    id: "tree-acer-palmatum-japanese-maple",
    name: "Japanese Maple",
    botanicalName: "Acer palmatum",
    kind: "plant",
    zoneMin: 5,
    zoneMax: 8,
    sun: ["part_sun", "part_shade"],
    matureHeightFt: 20,
    matureSpreadFt: 20,
    spacingFt: 18,
    native: false,
    invasive: false,
    deerRating: "B",
    unit: "each",
    unitPrice: 220,
    installLaborMinutes: 80,
  },

  // ------------------------------------------------------------------ SHRUBS (12)
  {
    id: "shrub-hydrangea-paniculata-limelight",
    name: "Panicle Hydrangea 'Limelight'",
    botanicalName: "Hydrangea paniculata 'Limelight'",
    kind: "plant",
    zoneMin: 3,
    zoneMax: 8,
    sun: ["full_sun", "part_sun"],
    matureHeightFt: 7,
    matureSpreadFt: 7,
    spacingFt: 6,
    native: false,
    invasive: false,
    deerRating: "C",
    unit: "each",
    unitPrice: 45,
    installLaborMinutes: 30,
  },
  {
    id: "shrub-ilex-glabra-inkberry",
    name: "Inkberry Holly",
    botanicalName: "Ilex glabra",
    kind: "plant",
    zoneMin: 4,
    zoneMax: 9,
    sun: ["full_sun", "part_sun", "part_shade"],
    matureHeightFt: 6,
    matureSpreadFt: 6,
    spacingFt: 5,
    native: true,
    invasive: false,
    deerRating: "B",
    unit: "each",
    unitPrice: 40,
    installLaborMinutes: 28,
  },
  {
    id: "shrub-itea-virginica-sweetspire",
    name: "Virginia Sweetspire 'Little Henry'",
    botanicalName: "Itea virginica 'Little Henry'",
    kind: "plant",
    zoneMin: 5,
    zoneMax: 9,
    sun: ["full_sun", "part_sun", "part_shade"],
    matureHeightFt: 3,
    matureSpreadFt: 3,
    spacingFt: 3,
    native: true,
    invasive: false,
    deerRating: "B",
    unit: "each",
    unitPrice: 35,
    installLaborMinutes: 25,
  },
  {
    id: "shrub-buxus-boxwood",
    name: "Boxwood 'Green Velvet'",
    botanicalName: "Buxus 'Green Velvet'",
    kind: "plant",
    zoneMin: 5,
    zoneMax: 8,
    sun: ["full_sun", "part_sun", "part_shade"],
    matureHeightFt: 3,
    matureSpreadFt: 3,
    spacingFt: 3,
    native: false,
    invasive: false,
    deerRating: "A",
    unit: "each",
    unitPrice: 50,
    installLaborMinutes: 30,
  },
  {
    id: "shrub-viburnum-dentatum-arrowwood",
    name: "Arrowwood Viburnum",
    botanicalName: "Viburnum dentatum",
    kind: "plant",
    zoneMin: 3,
    zoneMax: 8,
    sun: ["full_sun", "part_sun", "part_shade"],
    matureHeightFt: 8,
    matureSpreadFt: 8,
    spacingFt: 7,
    native: true,
    invasive: false,
    deerRating: "B",
    unit: "each",
    unitPrice: 42,
    installLaborMinutes: 30,
  },
  {
    id: "shrub-spiraea-japonica-goldmound",
    name: "Japanese Spirea 'Goldmound'",
    botanicalName: "Spiraea japonica 'Goldmound'",
    kind: "plant",
    zoneMin: 4,
    zoneMax: 8,
    sun: ["full_sun"],
    matureHeightFt: 3,
    matureSpreadFt: 3,
    spacingFt: 3,
    native: false,
    invasive: false,
    deerRating: "B",
    unit: "each",
    unitPrice: 30,
    installLaborMinutes: 25,
  },
  {
    id: "shrub-cornus-sericea-red-twig-dogwood",
    name: "Red-Twig Dogwood",
    botanicalName: "Cornus sericea",
    kind: "plant",
    zoneMin: 3,
    zoneMax: 7,
    sun: ["full_sun", "part_sun"],
    matureHeightFt: 8,
    matureSpreadFt: 8,
    spacingFt: 6,
    native: true,
    invasive: false,
    deerRating: "C",
    unit: "each",
    unitPrice: 38,
    installLaborMinutes: 28,
  },
  {
    id: "shrub-rhododendron-catawbiense",
    name: "Catawba Rhododendron",
    botanicalName: "Rhododendron catawbiense",
    kind: "plant",
    zoneMin: 4,
    zoneMax: 8,
    sun: ["part_sun", "part_shade"],
    matureHeightFt: 8,
    matureSpreadFt: 8,
    spacingFt: 6,
    native: true,
    invasive: false,
    deerRating: "D",
    unit: "each",
    unitPrice: 55,
    installLaborMinutes: 32,
  },
  {
    id: "shrub-juniperus-horizontalis-creeping-juniper",
    name: "Creeping Juniper 'Blue Rug'",
    botanicalName: "Juniperus horizontalis 'Wiltonii'",
    kind: "plant",
    zoneMin: 3,
    zoneMax: 9,
    sun: ["full_sun"],
    matureHeightFt: 1,
    matureSpreadFt: 8,
    spacingFt: 5,
    native: true,
    invasive: false,
    deerRating: "A",
    unit: "each",
    unitPrice: 28,
    installLaborMinutes: 22,
  },
  {
    id: "shrub-hydrangea-quercifolia-oakleaf",
    name: "Oakleaf Hydrangea",
    botanicalName: "Hydrangea quercifolia",
    kind: "plant",
    zoneMin: 5,
    zoneMax: 9,
    sun: ["part_sun", "part_shade"],
    matureHeightFt: 6,
    matureSpreadFt: 6,
    spacingFt: 6,
    native: true,
    invasive: false,
    deerRating: "C",
    unit: "each",
    unitPrice: 48,
    installLaborMinutes: 30,
  },
  {
    id: "shrub-rosa-rugosa",
    name: "Rugosa Rose",
    botanicalName: "Rosa rugosa",
    kind: "plant",
    zoneMin: 2,
    zoneMax: 7,
    sun: ["full_sun"],
    matureHeightFt: 5,
    matureSpreadFt: 5,
    spacingFt: 4,
    native: false,
    invasive: false,
    deerRating: "C",
    unit: "each",
    unitPrice: 36,
    installLaborMinutes: 26,
  },
  {
    id: "shrub-abelia-grandiflora",
    name: "Glossy Abelia 'Kaleidoscope'",
    botanicalName: "Abelia x grandiflora 'Kaleidoscope'",
    kind: "plant",
    zoneMin: 6,
    zoneMax: 9,
    sun: ["full_sun", "part_sun"],
    matureHeightFt: 3,
    matureSpreadFt: 4,
    spacingFt: 3,
    native: false,
    invasive: false,
    deerRating: "A",
    unit: "each",
    unitPrice: 34,
    installLaborMinutes: 25,
  },

  // ----------------------------------------- PERENNIALS / GRASSES / GROUNDCOVER (8)
  {
    id: "perennial-hemerocallis-daylily-stella",
    name: "Daylily 'Stella de Oro'",
    botanicalName: "Hemerocallis 'Stella de Oro'",
    kind: "plant",
    zoneMin: 3,
    zoneMax: 9,
    sun: ["full_sun", "part_sun"],
    matureHeightFt: 1,
    matureSpreadFt: 1.5,
    spacingFt: 1.5,
    native: false,
    invasive: false,
    deerRating: "C",
    unit: "each",
    unitPrice: 14,
    installLaborMinutes: 12,
  },
  {
    id: "perennial-echinacea-purpurea-coneflower",
    name: "Purple Coneflower",
    botanicalName: "Echinacea purpurea",
    kind: "plant",
    zoneMin: 3,
    zoneMax: 8,
    sun: ["full_sun", "part_sun"],
    matureHeightFt: 3,
    matureSpreadFt: 1.5,
    spacingFt: 1.5,
    native: true,
    invasive: false,
    deerRating: "B",
    unit: "each",
    unitPrice: 13,
    installLaborMinutes: 12,
  },
  {
    id: "perennial-rudbeckia-fulgida-black-eyed-susan",
    name: "Black-Eyed Susan 'Goldsturm'",
    botanicalName: "Rudbeckia fulgida 'Goldsturm'",
    kind: "plant",
    zoneMin: 4,
    zoneMax: 9,
    sun: ["full_sun", "part_sun"],
    matureHeightFt: 2.5,
    matureSpreadFt: 2,
    spacingFt: 1.5,
    native: true,
    invasive: false,
    deerRating: "B",
    unit: "each",
    unitPrice: 13,
    installLaborMinutes: 12,
  },
  {
    id: "grass-panicum-virgatum-switchgrass",
    name: "Switchgrass 'Heavy Metal'",
    botanicalName: "Panicum virgatum 'Heavy Metal'",
    kind: "plant",
    zoneMin: 4,
    zoneMax: 9,
    sun: ["full_sun"],
    matureHeightFt: 5,
    matureSpreadFt: 2.5,
    spacingFt: 3,
    native: true,
    invasive: false,
    deerRating: "A",
    unit: "each",
    unitPrice: 18,
    installLaborMinutes: 15,
  },
  {
    id: "grass-carex-pensylvanica-sedge",
    name: "Pennsylvania Sedge",
    botanicalName: "Carex pensylvanica",
    kind: "plant",
    zoneMin: 3,
    zoneMax: 8,
    sun: ["part_shade", "full_shade"],
    matureHeightFt: 0.8,
    matureSpreadFt: 1,
    spacingFt: 1,
    native: true,
    invasive: false,
    deerRating: "A",
    unit: "each",
    unitPrice: 12,
    installLaborMinutes: 10,
  },
  {
    id: "groundcover-liriope-muscari",
    name: "Lilyturf 'Big Blue'",
    botanicalName: "Liriope muscari 'Big Blue'",
    kind: "plant",
    zoneMin: 5,
    zoneMax: 10,
    sun: ["full_sun", "part_sun", "part_shade", "full_shade"],
    matureHeightFt: 1.5,
    matureSpreadFt: 1.5,
    spacingFt: 1,
    native: false,
    invasive: false,
    deerRating: "A",
    unit: "each",
    unitPrice: 11,
    installLaborMinutes: 10,
  },
  {
    id: "perennial-sedum-autumn-joy",
    name: "Stonecrop 'Autumn Joy'",
    botanicalName: "Hylotelephium 'Herbstfreude' (Sedum 'Autumn Joy')",
    kind: "plant",
    zoneMin: 3,
    zoneMax: 9,
    sun: ["full_sun"],
    matureHeightFt: 2,
    matureSpreadFt: 2,
    spacingFt: 1.5,
    native: false,
    invasive: false,
    deerRating: "A",
    unit: "each",
    unitPrice: 13,
    installLaborMinutes: 12,
  },
  {
    id: "perennial-salvia-nemorosa",
    name: "Wood Sage 'May Night'",
    botanicalName: "Salvia nemorosa 'Mainacht'",
    kind: "plant",
    zoneMin: 4,
    zoneMax: 8,
    sun: ["full_sun"],
    matureHeightFt: 1.5,
    matureSpreadFt: 1.5,
    spacingFt: 1.5,
    native: false,
    invasive: false,
    deerRating: "A",
    unit: "each",
    unitPrice: 13,
    installLaborMinutes: 12,
  },

  // ------------------------------------------------- MATERIALS / HARDSCAPE (8)
  // No zone fields — materials are always included by seedForZone and selectPlants.
  {
    id: "material-shredded-hardwood-mulch",
    name: "Shredded Hardwood Mulch",
    kind: "mulch",
    native: false,
    invasive: false,
    unit: "cuyd",
    unitPrice: 45,
    installLaborMinutes: 25,
  },
  {
    id: "material-river-rock",
    name: "River Rock (1-3 in)",
    kind: "mulch",
    native: false,
    invasive: false,
    unit: "cuyd",
    unitPrice: 95,
    installLaborMinutes: 40,
  },
  {
    id: "material-steel-landscape-edging",
    name: "Steel Landscape Edging (1/8 in)",
    kind: "edging",
    native: false,
    invasive: false,
    unit: "linft",
    unitPrice: 6.5,
    installLaborMinutes: 6,
  },
  {
    id: "material-concrete-paver",
    name: "Concrete Paver Patio",
    kind: "hardscape",
    native: false,
    invasive: false,
    unit: "sqft",
    unitPrice: 7,
    installLaborMinutes: 18,
  },
  {
    id: "material-flagstone",
    name: "Natural Flagstone Patio",
    kind: "hardscape",
    native: false,
    invasive: false,
    unit: "sqft",
    unitPrice: 16,
    installLaborMinutes: 24,
  },
  {
    id: "material-boulder-accent",
    name: "Landscape Boulder (accent, 18-30 in)",
    kind: "structure",
    native: false,
    invasive: false,
    unit: "each",
    unitPrice: 140,
    installLaborMinutes: 45,
  },
  {
    id: "material-pine-straw-bale",
    name: "Pine Straw Mulch (bale)",
    kind: "mulch",
    native: false,
    invasive: false,
    unit: "each",
    unitPrice: 7,
    installLaborMinutes: 5,
  },
  {
    id: "material-topsoil",
    name: "Screened Topsoil",
    kind: "structure",
    native: false,
    invasive: false,
    unit: "cuyd",
    unitPrice: 38,
    installLaborMinutes: 20,
  },
];

/**
 * Items whose hardiness band [zoneMin, zoneMax] includes the given zone.
 *
 * - Non-plant materials (and any item lacking BOTH zoneMin and zoneMax) carry no zone and
 *   are ALWAYS included — mirroring selectPlants(), which never zone-filters materials.
 * - When `zone` is null/undefined/non-finite, zone filtering is skipped and the full
 *   catalog is returned (honest default: we don't know the site, so don't drop anything).
 * - An item with only one bound is treated as open on the missing side.
 */
export function seedForZone(zone: number | null | undefined): PlantCatalogItem[] {
  const z = typeof zone === "number" && Number.isFinite(zone) ? zone : null;
  if (z === null) return PLANT_CATALOG_SEED.slice();

  return PLANT_CATALOG_SEED.filter((item) => {
    const hasBand =
      typeof item.zoneMin === "number" || typeof item.zoneMax === "number";
    if (!hasBand) return true; // materials / zone-agnostic items: always included
    const min = typeof item.zoneMin === "number" ? item.zoneMin : -Infinity;
    const max = typeof item.zoneMax === "number" ? item.zoneMax : Infinity;
    return z >= min && z <= max;
  });
}
