import React, { useState } from "react";
import { Sparkles, CheckCircle2, AlertTriangle, ShieldCheck, Mail, ArrowRight, Loader2, ListFilter, Send, X } from "lucide-react";
import { Customer } from "../types";
import { fetchApi } from "../lib/api";
import { motion, AnimatePresence } from "motion/react";
import { useToast } from "../contexts/ToastContext";

interface OutboundDraft {
  customerId: string;
  subject: string;
  body: string;
}

export function AutonomousCampaigns({ customers }: { customers: Customer[] }) {
  const { showToast } = useToast();
  const [agreementAccepted, setAgreementAccepted] = useState(false);
  const [targetService, setTargetService] = useState("");
  const [customInstructions, setCustomInstructions] = useState("");
  const [segment, setSegment] = useState<"all" | "priority" | "lapsed">("priority");
  
  const [isDrafting, setIsDrafting] = useState(false);
  const [drafts, setDrafts] = useState<OutboundDraft[]>([]);
  const [currentReviewIndex, setCurrentReviewIndex] = useState(0);

  const filteredCustomers = customers.filter(c => {
    if (segment === "all") return true;
    if (segment === "priority") return c.aiScore && c.aiScore >= 80;
    if (segment === "lapsed") return c.aiScore && c.aiScore < 40;
    return true;
  }).slice(0, 5); // Limit to 5 for safety/demo

  const handleGenerateDrafts = async () => {
    if (!targetService) {
        showToast("Please enter a target service or offer.", "error");
        return;
    }
    setIsDrafting(true);
    try {
        const payload = {
            targetService,
            instructions: customInstructions,
            customers: filteredCustomers.map(c => ({
                id: c.id,
                name: c.firstName + " " + c.lastName,
                address: c.address,
                notes: c.notes,
                tags: c.tags,
                score: c.aiScore
            }))
        };
        const res = await fetchApi("/api/outbound/draft-personalized-campaign", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload)
        });
        const data = await res.json();
        if (data.drafts) {
            setDrafts(data.drafts);
            setCurrentReviewIndex(0);
        }
    } catch(e) {
        showToast("Error generating drafts.", "error");
    } finally {
        setIsDrafting(false);
    }
  };

  const handleApprove = () => {
      showToast("Email Scheduled for Sending!");
      if (currentReviewIndex < drafts.length - 1) {
          setCurrentReviewIndex(prev => prev + 1);
      } else {
          setDrafts([]);
          showToast("Campaign Review Complete! All approved emails are in the outgoing queue.");
      }
  };

  const handleReject = () => {
      showToast("Draft Rejected and discarded.");
      if (currentReviewIndex < drafts.length - 1) {
          setCurrentReviewIndex(prev => prev + 1);
      } else {
          setDrafts([]);
          showToast("Campaign Review Complete!");
      }
  };

  if (!agreementAccepted) {
      return (
          <div className="max-w-2xl mx-auto p-8 bg-zinc-900 border-2 border-amber-500/30 rounded-3xl mt-8">
              <div className="w-16 h-16 bg-amber-500/10 text-amber-500 rounded-2xl flex items-center justify-center mb-6 border border-amber-500/20">
                  <ShieldCheck size={32} />
              </div>
              <h2 className="text-2xl font-black uppercase tracking-tight text-white mb-4">Autonomous Outbound Agreement</h2>
              <div className="space-y-4 text-sm text-zinc-300 leading-relaxed font-medium mb-8">
                  <p>
                      You are about to activate the <strong>Autonomous Campaign Engine</strong>. This system uses AI to generate highly personalized, persuasive outreach emails based on your clients' CRM profiles.
                  </p>
                  <div className="p-4 bg-amber-500/10 border border-amber-500/20 rounded-xl">
                      <p className="text-amber-400 font-bold mb-2 flex items-center gap-2">
                          <AlertTriangle size={16} /> Human-In-The-Loop Required
                      </p>
                      <p className="text-amber-500/80 mb-3">
                          While YardWorx builds the drafts, <strong>you are ultimately responsible for the content sent to your clients.</strong> By proceeding, you agree that you will manually review and approve every email generated by the system before it is dispatched outward.
                      </p>
                      <div className="bg-black/30 p-4 rounded-lg border border-amber-500/10">
                          <p className="text-xs font-black uppercase tracking-widest text-amber-500 mb-2">Review Checklist & Legal Pitfalls</p>
                          <ul className="list-disc list-inside text-xs space-y-2 text-amber-500/70">
                              <li><strong>Pricing Hallucinations:</strong> The AI may invent unauthorized discounts or over-promise services. If a client accepts an AI-generated price, you may be legally required to honor it.</li>
                              <li><strong>CAN-SPAM / Privacy Compliance:</strong> You must ensure sent emails include an opt-out mechanism and your physical address. Avoid spamming clients.</li>
                              <li><strong>Over-Personalization (Creep Factor):</strong> The AI has access to memory notes. Ensure it doesn't mention sensitive client details (e.g., "Sorry about your divorce") in a sales pitch.</li>
                          </ul>
                      </div>
                  </div>
                  <p className="text-xs text-zinc-500">
                      Gaelworx AI and YardWorx are not liable for lost profits, damaged reputation, CAN-SPAM violations, or hallucinations resulting from automated communications. You stand as the final human-in-the-loop and accept full responsibility for all approved outbound communications.
                  </p>
              </div>
              
              <button 
                onClick={() => setAgreementAccepted(true)}
                className="w-full py-4 bg-emerald-600 hover:bg-emerald-500 text-white font-black uppercase tracking-widest text-sm rounded-xl transition-all shadow-lg shadow-emerald-500/20 flex items-center justify-center gap-2"
              >
                  <CheckCircle2 size={18} /> I Understood & Agree to Review Drafts
              </button>
          </div>
      );
  }

  if (drafts.length > 0) {
      const currentDraft = drafts[currentReviewIndex];
      const customer = customers.find(c => c.id === currentDraft.customerId);

      return (
          <div className="max-w-4xl mx-auto space-y-6 mt-8">
              <div className="flex items-center justify-between">
                  <h3 className="text-xl font-black uppercase tracking-tight text-white flex items-center gap-2">
                       <Mail className="text-emerald-500" /> Review Queue
                  </h3>
                  <div className="px-4 py-2 bg-zinc-900 border border-white/10 rounded-full text-xs font-bold font-mono text-zinc-400">
                      {currentReviewIndex + 1} OF {drafts.length} REMAINING
                  </div>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                  {/* Context Panel */}
                  <div className="lg:col-span-1 bg-zinc-900 border border-white/5 rounded-3xl p-6">
                      <h4 className="text-xs font-black uppercase tracking-widest text-zinc-500 mb-4">Target Profile</h4>
                      {customer ? (
                          <div className="space-y-4">
                              <div>
                                 <p className="font-bold text-white text-lg">{customer.firstName} {customer.lastName}</p>
                                 <p className="text-sm text-zinc-400 font-mono">{customer.address}</p>
                              </div>
                              <div className="inline-block px-3 py-1 bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 rounded-lg text-xs font-bold uppercase tracking-widest">
                                  AI Score: {customer.aiScore || "N/A"}
                              </div>
                              <div className="pt-4 border-t border-white/5">
                                  <p className="text-xs font-bold uppercase tracking-widest text-zinc-500 mb-2">Memory Notes</p>
                                  <p className="text-sm text-zinc-300 italic">"{customer.notes || "No notes on file."}"</p>
                              </div>
                          </div>
                      ) : (
                          <p className="text-zinc-500">Profile missing.</p>
                      )}
                  </div>

                  {/* Review Panel */}
                  <div className="lg:col-span-2 bg-zinc-900 border border-white/5 rounded-3xl p-6 flex flex-col">
                      <div className="mb-4">
                          <label className="text-xs font-black uppercase tracking-widest text-zinc-500 mb-2 block">Subject Line</label>
                          <input 
                              type="text" 
                              className="w-full bg-black/50 border border-white/10 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-emerald-500"
                              value={currentDraft.subject}
                              onChange={(e) => {
                                  const newDrafts = [...drafts];
                                  newDrafts[currentReviewIndex].subject = e.target.value;
                                  setDrafts(newDrafts);
                              }}
                          />
                      </div>
                      <div className="flex-1 mb-6">
                          <label className="text-xs font-black uppercase tracking-widest text-zinc-500 mb-2 block">Email Body</label>
                          <textarea 
                              className="w-full h-64 bg-black/50 border border-white/10 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-emerald-500 resize-none font-mono text-sm leading-relaxed"
                              value={currentDraft.body}
                              onChange={(e) => {
                                  const newDrafts = [...drafts];
                                  newDrafts[currentReviewIndex].body = e.target.value;
                                  setDrafts(newDrafts);
                              }}
                          />
                      </div>
                      <div className="flex gap-4">
                          <button 
                              onClick={handleReject}
                              className="flex-1 py-4 border-2 border-white/10 text-zinc-400 hover:text-white hover:bg-white/5 font-black uppercase tracking-widest text-sm rounded-xl flex items-center justify-center gap-2 transition-all"
                          >
                             <X size={18} /> Reject
                          </button>
                          <button 
                              onClick={handleApprove}
                              className="flex-1 py-4 bg-emerald-600 hover:bg-emerald-500 text-white font-black uppercase tracking-widest text-sm rounded-xl flex items-center justify-center gap-2 transition-all shadow-lg shadow-emerald-500/20"
                          >
                             <Send size={18} /> Approve & Send
                          </button>
                      </div>
                  </div>
              </div>
          </div>
      );
  }

  return (
    <div className="max-w-3xl mx-auto space-y-6 mt-8">
        <div className="bg-zinc-900 border border-white/5 rounded-3xl p-6 sm:p-8">
            <h3 className="text-xl font-black uppercase tracking-tight text-white flex items-center gap-2 mb-6">
                 <Sparkles className="text-emerald-500" /> Autonomous Campaign Engine
            </h3>
            
            <div className="space-y-6">
                <div>
                   <label className="block text-xs font-black uppercase tracking-widest text-zinc-500 mb-2">1. Select Target Segment</label>
                   <div className="flex gap-3">
                       <button onClick={() => setSegment("priority")} className={`flex-1 py-3 px-4 rounded-xl text-sm font-bold border-2 transition-all ${segment === "priority" ? "bg-emerald-500/10 border-emerald-500/50 text-emerald-400" : "border-white/10 text-zinc-400 hover:border-white/30"}`}>
                           Priority Leads (Score &gt; 80)
                       </button>
                       <button onClick={() => setSegment("lapsed")} className={`flex-1 py-3 px-4 rounded-xl text-sm font-bold border-2 transition-all ${segment === "lapsed" ? "bg-emerald-500/10 border-emerald-500/50 text-emerald-400" : "border-white/10 text-zinc-400 hover:border-white/30"}`}>
                           Lapsed Clients (Score &lt; 40)
                       </button>
                       <button onClick={() => setSegment("all")} className={`flex-1 py-3 px-4 rounded-xl text-sm font-bold border-2 transition-all ${segment === "all" ? "bg-emerald-500/10 border-emerald-500/50 text-emerald-400" : "border-white/10 text-zinc-400 hover:border-white/30"}`}>
                           Entire Database
                       </button>
                   </div>
                </div>

                <div>
                   <label className="block text-xs font-black uppercase tracking-widest text-zinc-500 mb-2">2. What are we selling?</label>
                   <input 
                      type="text" 
                      className="w-full bg-black/50 border border-white/10 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-emerald-500"
                      placeholder="e.g. Spring Aeration & Overseeding"
                      value={targetService}
                      onChange={(e) => setTargetService(e.target.value)}
                   />
                </div>

                <div>
                   <label className="block text-xs font-black uppercase tracking-widest text-zinc-500 mb-2">3. Strategic Directives (Optional)</label>
                   <textarea 
                      className="w-full h-24 bg-black/50 border border-white/10 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-emerald-500 resize-none"
                      placeholder="e.g. Mention our 10% early bird discount. Keep the tone friendly and southern."
                      value={customInstructions}
                      onChange={(e) => setCustomInstructions(e.target.value)}
                   />
                </div>

                <div className="pt-4 border-t border-white/5 flex items-center justify-between">
                    <p className="text-sm font-mono text-zinc-500">
                        Targeting <strong>{filteredCustomers.length}</strong> clients
                        <span className="ml-2 text-xs text-amber-500 bg-amber-500/10 px-2 py-1 rounded-md uppercase tracking-widest">Review Enforced</span>
                    </p>
                    <button 
                        onClick={handleGenerateDrafts}
                        disabled={isDrafting || !targetService || filteredCustomers.length === 0}
                        className="px-6 py-3 bg-emerald-600 hover:bg-emerald-500 text-white font-black uppercase tracking-widest text-sm rounded-xl transition-all shadow-lg shadow-emerald-500/20 disabled:opacity-50 disabled:grayscale flex items-center gap-2"
                    >
                        {isDrafting ? <Loader2 size={18} className="animate-spin" /> : <Sparkles size={18} />}
                        {isDrafting ? "Analyzing CRM Data..." : "Generate Pilot Drafts"}
                    </button>
                </div>
            </div>
        </div>
    </div>
  );
}
